---
title: "Sobre el repositorio"
author: "Por Emilia Barrientos, Pablo Campos, Nicolás Godoy, Monserrat Greene y Gonzalo
  López"
output:
  html_document:
    highlight: textmate
    theme: paper
    toc: yes
    code_folding: hide
    toc_float: true
editor_options: 
  markdown: 
    wrap: sentence
---

Repositorio correspondiente a la investigación *¿Cómo se distribuye la precariedad laboral en Chile? Una propuesta tipológica para analizar las condiciones de trabajo del sector servicios durante la pandemia*, elaborada por Emilia Barrientos, Pablo Campos, Monserrat Greene, Nicolás Godoy y Gonzalo López en el marco del curso Ciencia Social Abierta, dictado por el profesor Juan Carlos Castillo en la Facultad de Ciencias Sociales de la Universidad de Chile. 

La carpeta **input** contiene dos carpetas. La primera, _bib_, que contiene los archivos apa_csl.csl, el cual especifica el estilo de citación a partir de APA; y ciencia_abierta.bib, que incluye la información respecto de la bibliografía referenciada en la investigación. Por su parte, _data_ contiene el archivo data_proc.rds, datos procesados utilizados en el análisis final. 

Asimismo, la carpeta **procesamiento** contiene el código de procesamiento, en que se refinaron los datos de la Encuesta Suplementaria de Ingresos (ESI) en su versión 2020. El archivo _procesamiento.rmd_ es reproducible, y detalla los pasos seguidos para procesar los datos de manera adecuada para el análisis. 

En la carpeta raíz del repositorio, por último, se encuentra el archivo **paper.rmd**, en el cual se presenta la investigación sobre el análisis de la precariedad en el sector de servicios de la economía chilena. 